image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_tags: true

for:
-
    branches:
        only:
            - develop

    install:
        - ps: $env:version_file_path = ".\version.props"
        - ps: gitversion /output buildserver
        - ps: $env:major_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:minor_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:release_version = [string]([int]((Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText) + 1)
        - ps: $env:revision = $env:GitVersion_CommitsSinceVersionSource
        - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:revision.$env:APPVEYOR_BUILD_NUMBER"
        - ps: $xReleaseVersion = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion"
        - ps: $xReleaseVersion.Node.InnerText = $env:release_version
        - ps: $xReleaseVersion.Node.OwnerDocument.Save($xReleaseVersion.Path)
        - ps: $xRevision = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/Revision"
        - ps: $xRevision.Node.InnerText = $env:revision
        - ps: $xRevision.Node.OwnerDocument.Save($xRevision.Path)
        - ps: $xPackageSemanticVersionSuffix = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/PackageSemanticVersionSuffix"
        - ps: $xPackageSemanticVersionSuffix.Node.InnerText = "-alpha"
        - ps: $xPackageSemanticVersionSuffix.Node.OwnerDocument.Save($xPackageSemanticVersionSuffix.Path)

    on_success:
        - ps: git config --global credential.helper store
        - ps: Add-Content "$HOME\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
        - ps: git config --global user.email "$env:github_email"
        - ps: git config --global user.name "$env:github_name"
        - ps: git pull
        - git commit -m "Revision update by AppVeyor [ci skip]" -- version.props
        - git push

-
    branches:
        only:
            - master

    install:
        - ps: $env:version_file_path = ".\version.props"
        - ps: gitversion /output buildserver
        - ps: $env:major_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:minor_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:release_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:revision = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/Revision" | Select-Object -ExpandProperty Node).InnerText
        - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:revision.$env:APPVEYOR_BUILD_NUMBER"
        - ps: $xPackageSemanticVersionSuffix = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/PackageSemanticVersionSuffix"
        - ps: $xPackageSemanticVersionSuffix.Node.InnerText = "-beta"
        - ps: $xPackageSemanticVersionSuffix.Node.OwnerDocument.Save($xPackageSemanticVersionSuffix.Path)

-
    branches:
        only:
            - /rc-.*/

    install:
        - ps: $env:version_file_path = ".\version.props"
        - ps: gitversion /output buildserver
        - ps: $env:major_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:minor_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:release_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:revision = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/Revision" | Select-Object -ExpandProperty Node).InnerText
        - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:revision.$env:APPVEYOR_BUILD_NUMBER"
        - ps: $xPackageSemanticVersionSuffix = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/PackageSemanticVersionSuffix"
        - ps: $xPackageSemanticVersionSuffix.Node.InnerText = "-rc"
        - ps: $xPackageSemanticVersionSuffix.Node.OwnerDocument.Save($xPackageSemanticVersionSuffix.Path)

    on_success:
        - ps: # dotnet nuget push bin\Release\DotFramework.DynamicQuery.*.nupkg -k $env:nuget_api_key -s https://api.nuget.org/v3/index.json

-
    branches:
        only:
            - /release-.*/

    install:
        - ps: $env:version_file_path = ".\version.props"
        - ps: gitversion /output buildserver
        - ps: $env:major_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MajorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:minor_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/MinorVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:release_version = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/ReleaseVersion" | Select-Object -ExpandProperty Node).InnerText
        - ps: $env:revision = (Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/Revision" | Select-Object -ExpandProperty Node).InnerText
        - ps: Update-AppveyorBuild -Version "$env:major_version.$env:minor_version.$env:release_version.$env:revision.$env:APPVEYOR_BUILD_NUMBER"
        - ps: $xPackageSemanticVersionSuffix = Select-Xml -Path $env:version_file_path -XPath "/Project/PropertyGroup/PackageSemanticVersionSuffix"
        - ps: $xPackageSemanticVersionSuffix.Node.InnerText = ""
        - ps: $xPackageSemanticVersionSuffix.Node.OwnerDocument.Save($xPackageSemanticVersionSuffix.Path)

    on_success:
        - ps: # dotnet nuget push bin\Release\DotFramework.DynamicQuery.*.nupkg -k $env:nuget_api_key -s https://api.nuget.org/v3/index.json

dotnet_csproj:
    patch: false

before_build:
    - cmd: dotnet restore "source\DynamicQuery.sln"

build:
    project: source\DynamicQuery.sln
    parallel: true
    verbosity: minimal

after_build:
    

after_test:
    

artifacts:
    - path: 'bin\Release\DotFramework.DynamicQuery.*.nupkg'
      name: 'DotFramework.DynamicQuery'